version: '3.1'

services:
  web:
    build: .
    command:
       sh -c python manage.py wait_for_db &&
             python manage.py migrate 
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
        - db
  db:
    image: postgres 
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    ports:
        - "5432:5432"
