# Generated by Django 3.2.3 on 2021-06-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0003_auto_20210602_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
    ]
