# Generated by Django 3.2.3 on 2021-06-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0004_remove_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('C', 'Completed'), ('T', 'To be done')], max_length=1, null=True),
        ),
    ]
