# Generated by Django 3.2.3 on 2021-06-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0005_task_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-done'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
